fitness_app/config/routes.rb
Rails.application.routes.draw do

  resources :users do
    resources :workouts do 
      resources :exercises
    end
  end

  resources :articles do 
    resources :comments
  end

  resources :categories

  resources :exercises

  resources :posts do 
    member do 
      get "like", to: 'posts#upvote'
      get "dislike", to: 'posts#downvote'
    end
    resources :comments
  end

  get "/motivation", to: "motivation#index"

  get "categories/:id/articles", to: "articles#catindex", as: 'catindex'

  get 'welcome/index'

  root 'welcome#index'

  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'

  

end

fitness_app/app/models/article.rb
class Article < ActiveRecord::Base
	belongs_to :category
	has_many :comments
end

fitness_app/app/models/category.rb
class Category < ActiveRecord::Base
	has_many :articles
end

fitness_app/app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  belongs_to :user
  belongs_to :article
end

fitness_app/app/models/exercise.rb
class Exercise < ActiveRecord::Base
	belongs_to :routine
end

fitness_app/app/models/post.rb
class Post < ActiveRecord::Base

	acts_as_votable

	belongs_to :user
	has_many :comments

	validates :title, presence: true
	validates :link, presence: true

	has_attached_file :image, styles: { medium: "700x500#", small: "350x250#" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/

end

fitness_app/app/models/routine.rb
class Routine < ActiveRecord::Base
	belongs_to :workout
	has_many :users, through: :workouts
	has_many :exercises
	serialize :reps, Array
	serialize :weight, Array
end

fitness_app/app/models/user.rb
class User < ActiveRecord::Base

  has_many :workouts
  has_many :routines, through: :workouts
  has_many :posts
  has_many :comments

	 def self.from_omniauth(auth)
    user = User.find_or_create_by(provider: auth.provider, uid: auth.uid)
    user.name = auth.info.name
    user.email = auth.info.email

    user.oauth_token = auth.credentials.token
    user.oauth_expires_at = Time.at(auth.credentials.expires_at)

    user.save!

    user
  end

  def facebook
    @facebook ||= Koala::Facebook::API.new(oauth_token)
  end

end

fitness_app/app/models/workout.rb
class Workout < ActiveRecord::Base
	has_many :routines #dependant: :destroy 
	belongs_to :user
	accepts_nested_attributes_for :routines, allow_destroy: true
	validates_presence_of :title
end

fitness_app/app/controllers/admin_controller.rb
class AdminController < ApplicationController

	before_filter :authorized?

  private

  def authorized?
    unless current_user.has_role? :admin
      flash[:error] = "You are not authorized to view that page."
      redirect_to articles_path
    end
  end

end

fitness_app/app/helpers/admin_helper.rb
module AdminHelper
end

fitness_app/app/helpers/application_helper.rb
module ApplicationHelper
end

fitness_app/app/helpers/article_helper.rb
module ArticleHelper
end

fitness_app/app/helpers/articles_helper.rb
module ArticlesHelper
end

fitness_app/app/helpers/category_helper.rb
module CategoryHelper
end

fitness_app/app/helpers/comments_helper.rb
module CommentsHelper
end

fitness_app/app/helpers/exercises_helper.rb
module ExercisesHelper
end

fitness_app/app/helpers/motivation_helper.rb
module MotivationHelper
end

fitness_app/app/helpers/posts_helper.rb
module PostsHelper
end

fitness_app/app/helpers/welcome_helper.rb
module WelcomeHelper
end

fitness_app/app/helpers/workouts_helper.rb
module WorkoutsHelper
end

fitness_app/app/views/layouts/_header.html.erb
<div class="row">
    <div class="col span_3 button button-primary button-selected">
      <p><%= link_to "Workouts", user_workouts_path(@user) %></p>
    </div>
    <div class="col span_3 button button-primary">
      <p><%= link_to "Articles", articles_path %></p>
    </div>
    <div class="col span_3 button button-primary">
      <p><%= link_to "Exercises", exercises_path %></p>
    </div>
    <div class="col span_3 button button-primary">
      <p><%= link_to "Motivation", posts_path %></p>
    </div>
  </div>
</div>

fitness_app/app/views/layouts/_navbar.html.erb
<header>
  <div class="wrapper" class="clearfix">
    <div id="logo">
      <%= link_to "HOME", articles_path %>
    </div>
    <nav>
      <% if current_user %>
        <%= link_to current_user.name, "#" %>
        <%= link_to "Sign out", signout_path, id: "sign_out" %>
      <% else %>
        <%= link_to "Sign in with Facebook", "/auth/facebook", id: "sign_in" %>
      <% end %>
    </nav>
  </div>
</header>

fitness_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FitnessApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <link rel="stylesheet" href="http://cdnjs.cloudflare.com/ajax/libs/normalize/3.0.1/normalize.min.css">
  <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.>css">
  <%= csrf_meta_tags %>
</head>

<body>
	
<p class="notice">
	<%= notice %>
</p>
<p class="alert">
	<%= alert %>
</p>
<div class="wrapper">
<%= yield %>
</div>

</body>
</html>

fitness_app/app/views/partial/_navbar.html.erb
<div class="band navigation">
  <div class="row">
    <div class="col span_3 button button-primary button-selected">
      <p><%= link_to "Workouts", user_workouts_path(@user) %></p>
    </div>
    <div class="col span_3 button button-primary">
      <p><%= link_to "Articles", articles_path %></p>
    </div>
    <div class="col span_3 button button-primary">
      <p><%= link_to "Exercises", exercises_path %></p>
    </div>
    <div class="col span_3 button button-primary">
      <p><%= link_to "Motivation"%></p>
    </div>
  </div>
</div>