fitness_app/config/routes.rb
Rails.application.routes.draw do

  resources :users do
    resources :workouts do 
      resources :exercises
    end
  end

  resources :articles do 
    resources :comments
  end

  resources :categories

  resources :exercises

  resources :posts do 
    member do 
      get "like", to: 'posts#upvote'
      get "dislike", to: 'posts#downvote'
    end
    resources :comments
  end

  get "/motivation", to: "motivation#index"

  get "categories/:id/articles", to: "articles#catindex", as: 'catindex'

  get 'welcome/index'

  root 'welcome#index'

  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'

  

end

fitness_app/app/models/article.rb
class Article < ActiveRecord::Base
	belongs_to :category
	has_many :comments
end

fitness_app/app/models/category.rb
class Category < ActiveRecord::Base
	has_many :articles
end

fitness_app/app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  belongs_to :user
  belongs_to :article
end

fitness_app/app/models/exercise.rb
class Exercise < ActiveRecord::Base
	belongs_to :routine
end

fitness_app/app/models/post.rb
class Post < ActiveRecord::Base

	acts_as_votable

	belongs_to :user
	has_many :comments

	validates :title, presence: true
	validates :link, presence: true

	has_attached_file :image, styles: { medium: "700x500#", small: "350x250#" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/

end

fitness_app/app/models/routine.rb
class Routine < ActiveRecord::Base
	belongs_to :workout
	has_many :users, through: :workouts
	has_many :exercises
	serialize :reps, Array
	serialize :weight, Array
end

fitness_app/app/models/user.rb
class User < ActiveRecord::Base

  has_many :workouts
  has_many :routines, through: :workouts
  has_many :posts
  has_many :comments

	 def self.from_omniauth(auth)
    user = User.find_or_create_by(provider: auth.provider, uid: auth.uid)
    user.name = auth.info.name
    user.email = auth.info.email

    user.oauth_token = auth.credentials.token
    user.oauth_expires_at = Time.at(auth.credentials.expires_at)

    user.save!

    user
  end

  def facebook
    @facebook ||= Koala::Facebook::API.new(oauth_token)
  end

end

fitness_app/app/models/workout.rb
class Workout < ActiveRecord::Base
	has_many :routines #dependant: :destroy 
	belongs_to :user
	accepts_nested_attributes_for :routines, allow_destroy: true
	validates_presence_of :title
end

fitness_app/app/controllers/admin_controller.rb
class AdminController < ApplicationController

	before_filter :authorized?

  private

  def authorized?
    unless current_user.has_role? :admin
      flash[:error] = "You are not authorized to view that page."
      redirect_to articles_path
    end
  end

end

fitness_app/app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	# before_action :set_article
	before_action :authenticate, except: [:index, :show]

	def index
		@user = User.find_by(uid: params[:uid])
		@articles = Article.all
		@workout_articles = Category.find_by(name: "Workout").articles
		@nutrition_articles = Category.find_by(name: "Nutrition").articles
		@motivation_articles = Category.find_by(name: "Motivation").articles
		@supplement_articles = Category.find_by(name: "Supplemention").articles
		@humor_articles = Category.find_by(name: "Humor").articles
	end

	def show
		@article = Article.find(params[:id])
		@random_article = Article.where.not(id: @article).order("RANDOM()").first
	end

	def catindex
		@article_cat = Category.find(params[:id])
		@articles = Category.find(params[:id]).articles
	end

	private

	def authenticate
		authenticate_or_request_with_http_basic do |name, password|
			name = "admin" && password == "secret"
		end
	end
end

fitness_app/app/controllers/posts_controller.rb
class PostsController < ApplicationController
 
  before_action :find_post, only: [:show, :edit, :update, :destroy, :upvote, :downvote]

  def index
    @posts = Post.all.order("created_at DESC")
  end

  def new
    if current_user
      @post = current_user.posts.build
    else
      redirect_to new_user_registration_path
    end
  end

  def show
    @comments = Comment.where(post_id: @post)
    @random_post = Post.where.not(id: @post).order("RANDOM()").first
  end

  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      redirect_to post_path(@post), notice: "Successfully Added Post"
    else
      render 'new', notice: "Failed to Add Post"
    end
  end

  def edit
  end

  def update
    if @post.update(post_params)
      redirect_to post_path(@post), notice: "Successfully Updated Post"
    else
      redirect_to :back, notice: "Failed to Update Post"
    end
  end

  def destroy
    if @post.delete 
      redirect_to posts_path, notice: "Successfully Deleted Post"
    else
      redirect_to :back
    end
  end

  def upvote
    @post.upvote_by current_user
    redirect_to :back
  end

  def downvote
    @post.downvote_by current_user
    redirect_to :back
  end

  private

  def find_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :link, :description, :image)
  end
end

fitness_app/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

fitness_app/app/helpers/admin_helper.rb
module AdminHelper
end

fitness_app/app/helpers/application_helper.rb
module ApplicationHelper
end

fitness_app/app/helpers/article_helper.rb
module ArticleHelper
end

fitness_app/app/helpers/articles_helper.rb
module ArticlesHelper
end

fitness_app/app/helpers/category_helper.rb
module CategoryHelper
end

fitness_app/app/helpers/comments_helper.rb
module CommentsHelper
end

fitness_app/app/helpers/exercises_helper.rb
module ExercisesHelper
end

fitness_app/app/helpers/motivation_helper.rb
module MotivationHelper
end

fitness_app/app/helpers/posts_helper.rb
module PostsHelper
end

fitness_app/app/helpers/welcome_helper.rb
module WelcomeHelper
end

fitness_app/app/helpers/workouts_helper.rb
module WorkoutsHelper
end

fitness_app/app/views/posts/_form.html.haml
%div.container
	= simple_form_for @post do |f|
		= f.input :image
		= f.input :title
		= f.input :link
		= f.input :description

		= f.button :submit

fitness_app/app/views/posts/_navbar.html.haml
%body
	%header
		.wrapper.clearfix

			#logo= link_to "FIT-SPIRATION", articles_path
			%nav
				- if current_user
					= link_to current_user.name, "#"
					= link_to "Add New Inspiration", new_post_path, class: "button"
				- else
					= link_to "Sign in", "#"
					= link_to "Sign Up", "#", class: "button"

fitness_app/app/views/posts/_navbar_posts.html.haml
%body
	%header
		.wrapper.clearfix

			#logo= link_to "FIT-SPIRATION", articles_path
			%nav
				- if current_user
					= link_to current_user.name, "#"
					= link_to "Add New Inspiration", new_post_path, class: "button"
				- else
					= link_to "Sign in", "#"
					= link_to "Sign Up", "#", class: "button"

fitness_app/app/views/posts/edit.html.haml
= render 'layouts/navbar'
%h1 Edit Inspiration

= render 'form'

fitness_app/app/views/posts/index.html.haml
= render 'navbar_posts'
- if current_user
	%p#intro
		Hello
		= current_user.name
		%br/
		%span
			Post your motivational quote or photo
- else
	%p#intro
		What's your Fit-Spiration?
		%br/
		%span
			Share your inspiration and see what's inspiring others.
#posts
	- @posts.each do |post|
		.post
			.post_image
				= link_to (image_tag post.image.url(:small)), post
			.post_content
				.title
					%h2= link_to post.title, post
				.data.clearfix
					%p.username
						Shared by
						= post.user.name
					%p.buttons
						%span
							%i.fa.fa-comments-o
							= post.comments.count
						%span
							%i.fa.fa-thumbs-o-up
							= post.get_likes.size

fitness_app/app/views/posts/new.html.haml
%h1 Add Inspiration

= render 'form'

fitness_app/app/views/posts/show.html.haml
= render 'navbar_posts'
#post_show
	%h1= @post.title
	%p.username
		Shared by
		= @post.user.name
		= time_ago_in_words(@post.created_at)
	.clearfix
		.post_image_description
			= image_tag @post.image.url(:medium)
			.description= simple_format(@post.description)
		.post_data
			= link_to "Visit Link", "http://"+@post.link, class: "button"
			= link_to like_post_path(@post), method: :get, class: "data" do
				%i.fa.fa-thumbs-o-up
				= pluralize(@post.get_upvotes.size, "Like")
			= link_to dislike_post_path(@post), method: :get, class: "data" do
				%i.fa.fa-thumbs-o-down
				= pluralize(@post.get_downvotes.size, "Dislike")
			%p.data
				%i.fa.fa-comments-o
				= pluralize(@post.comments.count, "Comment")
			- if @post.user == current_user
				= link_to "Edit", edit_post_path(@post), class: "data"
				= link_to "Delete", post_path(@post), method: :delete, data: { confirm: "Are you sure?" }, class: "data"
		#random_post
			%h3 Random Inspiration
			.post
				.post_image
					= link_to (image_tag @random_post.image.url(:medium)), post_path(@random_post)
				.post_content
					.title
						%h2= link_to @random_post.title, post_path(@random_post)
					.data.clearfix
						%p.username
							Shared by
							= @random_post.user.name
						%p.buttons
							%span
								%i.fa.fa-comments-o
								= @random_post.comments.count
							%span
								%i.fa.fa-thumbs-o-up
								= @random_post.get_likes.size

#comments
	%h2.comment_count= pluralize(@post.comments.count, "Comment")
	- @comments.each do |comment|
		.comment
			%p.username= comment.user.name
			%p.content= comment.content

	= render "comments/form"