fitness_app/config/routes.rb
Rails.application.routes.draw do

  resources :users do
    resources :workouts do 
      resources :exercises
    end
  end

  resources :articles do 
    resources :comments
  end

  resources :categories

  resources :exercises

  resources :posts do 
    member do 
      get "like", to: 'posts#upvote'
      get "dislike", to: 'posts#downvote'
    end
    resources :comments
  end

  get "/motivation", to: "motivation#index"

  get "categories/:id/articles", to: "articles#catindex", as: 'catindex'

  get 'welcome/index'

  root 'welcome#index'

  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'

  

end

fitness_app/app/models/article.rb
class Article < ActiveRecord::Base
	belongs_to :category
	has_many :comments
end

fitness_app/app/models/category.rb
class Category < ActiveRecord::Base
	has_many :articles
end

fitness_app/app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  belongs_to :user
  belongs_to :article
end

fitness_app/app/models/exercise.rb
class Exercise < ActiveRecord::Base
	belongs_to :routine
end

fitness_app/app/models/post.rb
class Post < ActiveRecord::Base

	acts_as_votable

	belongs_to :user
	has_many :comments

	validates :title, presence: true
	validates :link, presence: true

	has_attached_file :image, styles: { medium: "700x500#", small: "350x250#" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/

end

fitness_app/app/models/routine.rb
class Routine < ActiveRecord::Base
	belongs_to :workout
	has_many :users, through: :workouts
	has_many :exercises
	serialize :reps, Array
	serialize :weight, Array
end

fitness_app/app/models/user.rb
class User < ActiveRecord::Base

  has_many :workouts
  has_many :routines, through: :workouts
  has_many :posts
  has_many :comments

	 def self.from_omniauth(auth)
    user = User.find_or_create_by(provider: auth.provider, uid: auth.uid)
    user.name = auth.info.name
    user.email = auth.info.email

    user.oauth_token = auth.credentials.token
    user.oauth_expires_at = Time.at(auth.credentials.expires_at)

    user.save!

    user
  end

  def facebook
    @facebook ||= Koala::Facebook::API.new(oauth_token)
  end

end

fitness_app/app/models/workout.rb
class Workout < ActiveRecord::Base
	has_many :routines #dependant: :destroy 
	belongs_to :user
	accepts_nested_attributes_for :routines, allow_destroy: true
	validates_presence_of :title
end

fitness_app/app/controllers/admin_controller.rb
class AdminController < ApplicationController

	before_filter :authorized?

  private

  def authorized?
    unless current_user.has_role? :admin
      flash[:error] = "You are not authorized to view that page."
      redirect_to articles_path
    end
  end

end

fitness_app/app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	# before_action :set_article
	before_action :authenticate, except: [:index, :show]

	def index
		@user = User.find_by(uid: params[:uid])
		@articles = Article.all
		@workout_articles = Category.find_by(name: "Workout").articles
		@nutrition_articles = Category.find_by(name: "Nutrition").articles
		@motivation_articles = Category.find_by(name: "Motivation").articles
		@supplement_articles = Category.find_by(name: "Supplemention").articles
		@humor_articles = Category.find_by(name: "Humor").articles
	end

	def show
		@article = Article.find(params[:id])
		@random_article = Article.where.not(id: @article).order("RANDOM()").first
	end

	def catindex
		@article_cat = Category.find(params[:id])
		@articles = Category.find(params[:id]).articles
	end

	private

	def authenticate
		authenticate_or_request_with_http_basic do |name, password|
			name = "admin" && password == "secret"
		end
	end
end

fitness_app/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  
	def create
		p params
		@post = Post.find(params[:post_id])
		@comment = Comment.new(content: params[:comment][:content], post_id: params[:post_id], user_id: current_user.id)

		if @comment.save
			redirect_to post_path(@post)
		else
			render 'new'
		end
	end
	
end

fitness_app/app/controllers/posts_controller.rb
class PostsController < ApplicationController
 
  before_action :find_post, only: [:show, :edit, :update, :destroy, :upvote, :downvote]

  def index
    @posts = Post.all.order("created_at DESC")
  end

  def new
    if current_user
      @post = current_user.posts.build
    else
      redirect_to new_user_registration_path
    end
  end

  def show
    @comments = Comment.where(post_id: @post)
    @random_post = Post.where.not(id: @post).order("RANDOM()").first
  end

  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      redirect_to post_path(@post), notice: "Successfully Added Post"
    else
      render 'new', notice: "Failed to Add Post"
    end
  end

  def edit
  end

  def update
    if @post.update(post_params)
      redirect_to post_path(@post), notice: "Successfully Updated Post"
    else
      redirect_to :back, notice: "Failed to Update Post"
    end
  end

  def destroy
    if @post.delete 
      redirect_to posts_path, notice: "Successfully Deleted Post"
    else
      redirect_to :back
    end
  end

  def upvote
    @post.upvote_by current_user
    redirect_to :back
  end

  def downvote
    @post.downvote_by current_user
    redirect_to :back
  end

  private

  def find_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :link, :description, :image)
  end
end

fitness_app/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

fitness_app/app/helpers/admin_helper.rb
module AdminHelper
end

fitness_app/app/helpers/application_helper.rb
module ApplicationHelper
end

fitness_app/app/helpers/article_helper.rb
module ArticleHelper
end

fitness_app/app/helpers/articles_helper.rb
module ArticlesHelper
end

fitness_app/app/helpers/category_helper.rb
module CategoryHelper
end

fitness_app/app/helpers/comments_helper.rb
module CommentsHelper
end

fitness_app/app/helpers/exercises_helper.rb
module ExercisesHelper
end

fitness_app/app/helpers/motivation_helper.rb
module MotivationHelper
end

fitness_app/app/helpers/posts_helper.rb
module PostsHelper
end

fitness_app/app/helpers/welcome_helper.rb
module WelcomeHelper
end

fitness_app/app/helpers/workouts_helper.rb
module WorkoutsHelper
end

fitness_app/app/views/articles/catindex.html.erb
<%= render 'layouts/navbar' %>
<h1><%= @article_cat.name %> Articles</h1>

	<div><% @articles.each do |article| %>
		<h2><%= article.title %></h2>
			<div><img src="<%= article.image %>"></div>
		<h2><%= article.tag %></h2>
		<div><%= article.date %></div>
		<div><%= article.author %></div>
		<div><%= article.content %></div>
		</br>
	<% end %>

fitness_app/app/views/articles/index.html.erb
<%= render 'layouts/navbar' %>

	<header>
		<div class="wrapper" class="clearfix">

			<%= render 'layouts/header'%>

			<div class="row">
				<div class="col span_3">
					<h2>Workout Articles</h2>
					<h3><%= link_to "See All", catindex_path(1) %></h3>
					<div><% @workout_articles.each do |article| %>
						<div>
							<%= link_to article.title, article_path(article) %>
						</div>
						<div height="100px" class="index-image">
							<img src="<%= article.image %>" height="100" width="180">
						</div>
						<div><%= article.tag %></div>
						<div><%= article.date %></div>
						<div><%= article.author %></div>
						<% end %>
					</div>
				</div>

				<div class="row">
					<div class="col span_3">
						<h2>Nutritional Articles</h2>
						<h3><%= link_to "See All", catindex_path(2) %></h3>
						<div class="index-image"><% @nutrition_articles.each do |article| %>
							<%= link_to article.title, article_path(article) %></br>
							<div><img src="<%= article.image %>" height="100" width="180"></div>
							<%= article.tag %></br>
							<%= article.date %></br>
							<%= article.author %></br>
						</br>
						<% end %>
					</div>
				</div>

				<div class="row">
					<div class="col span_3">
						<h2>Motivational Articles</h2>
						<h3><%= link_to "See All", catindex_path(3) %></h3>
						<div><% @motivation_articles.each do |article| %>
							<%= link_to article.title, article_path(article) %></br>
							<div class="index-image"><img src="<%= article.image %>" height="100" width="180"></div>
							<%= article.tag %></br>
							<%= article.date %></br>
							<%= article.author %></br>
						</br>
						<% end %>
					</div>
				</div>

				<div class="row">
					<div class="col span_3">
						<h2>Supplementational Articles</h2>
						<h3><%= link_to "See All", catindex_path(4) %></h3>
						<div><% @supplement_articles.each do |article| %>
							<%= link_to article.title, article_path(article) %></br>
							<div class="index-image"><img src="<%= article.image %>" height="100" width="180"></div>
							<%= article.tag %></br>
							<%= article.date %></br>
							<%= article.author %></br>
						</br>
						<% end %>
					</div>
				</div>
			</header>

fitness_app/app/views/articles/show.html.erb
<%= render 'layouts/navbar' %>
<div id="post_show">
	<div class="clearfix">
		<div class="post_image_description">
			<h1><%= @article.title %></h1>
			<div><img src="<%= @article.image %>"></div>
			<h2><%= @article.tag %></h2>
			<div class="description">
				<div><%= @article.date %></div>
				<div><%= @article.author %></div>
				<div><%= @article.content %></div>
			</div>
		</div>
		<div id="random_post">
			<h3>Random Article</h3>
			<div class="post">
				<div class="post_image">
					<%= link_to (image_tag @random_article.image), article_path(@random_article) %>
				</div>
				<div class="post_content">
					<div class="title">
						<h2><%= link_to @random_article.title, article_path(@random_article)%></h2>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
<div id="comments">
	<h2 class="comment_count"><%= pluralize(@article.comments.count, "Comments")%></h2>
	<% @article.comments.each do |comment| %>
	<div class="comment">
		<p class="username"><%= comment.user%></p>
		<p class="content"><%= comment.content %></p>
	</div>
	<% end %>
	<%= render "comments/form_article" %>
</div>