fitness_app/config/routes.rb
Rails.application.routes.draw do

  resources :users do
    resources :workouts do 
      resources :exercises
    end
  end

  resources :articles do 
    resources :comments
  end

  resources :categories

  resources :exercises

  resources :posts do 
    member do 
      get "like", to: 'posts#upvote'
      get "dislike", to: 'posts#downvote'
    end
    resources :comments
  end

  get "/motivation", to: "motivation#index"

  get "categories/:id/articles", to: "articles#catindex", as: 'catindex'

  get 'welcome/index'

  root 'welcome#index'

  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'

  

end

fitness_app/app/models/article.rb
class Article < ActiveRecord::Base
	belongs_to :category
	has_many :comments
end

fitness_app/app/models/category.rb
class Category < ActiveRecord::Base
	has_many :articles
end

fitness_app/app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  belongs_to :user
  belongs_to :article
end

fitness_app/app/models/exercise.rb
class Exercise < ActiveRecord::Base
	belongs_to :routine
end

fitness_app/app/models/post.rb
class Post < ActiveRecord::Base

	acts_as_votable

	belongs_to :user
	has_many :comments

	validates :title, presence: true
	validates :link, presence: true

	has_attached_file :image, styles: { medium: "700x500#", small: "350x250#" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/

end

fitness_app/app/models/routine.rb
class Routine < ActiveRecord::Base
	belongs_to :workout
	has_many :users, through: :workouts
	has_many :exercises
	serialize :reps, Array
	serialize :weight, Array
end

fitness_app/app/models/user.rb
class User < ActiveRecord::Base

  has_many :workouts
  has_many :routines, through: :workouts
  has_many :posts
  has_many :comments

	 def self.from_omniauth(auth)
    user = User.find_or_create_by(provider: auth.provider, uid: auth.uid)
    user.name = auth.info.name
    user.email = auth.info.email

    user.oauth_token = auth.credentials.token
    user.oauth_expires_at = Time.at(auth.credentials.expires_at)

    user.save!

    user
  end

  def facebook
    @facebook ||= Koala::Facebook::API.new(oauth_token)
  end

end

fitness_app/app/models/workout.rb
class Workout < ActiveRecord::Base
	has_many :routines #dependant: :destroy 
	belongs_to :user
	accepts_nested_attributes_for :routines, allow_destroy: true
	validates_presence_of :title
end

fitness_app/app/controllers/admin_controller.rb
class AdminController < ApplicationController

	before_filter :authorized?

  private

  def authorized?
    unless current_user.has_role? :admin
      flash[:error] = "You are not authorized to view that page."
      redirect_to articles_path
    end
  end

end

fitness_app/app/controllers/posts_controller.rb
class PostsController < ApplicationController
 
  before_action :find_post, only: [:show, :edit, :update, :destroy, :upvote, :downvote]

  def index
    @posts = Post.all.order("created_at DESC")
  end

  def new
    if current_user
      @post = current_user.posts.build
    else
      redirect_to new_user_registration_path
    end
  end

  def show
    @comments = Comment.where(post_id: @post)
    @random_post = Post.where.not(id: @post).order("RANDOM()").first
  end

  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      redirect_to post_path(@post), notice: "Successfully Added Post"
    else
      render 'new', notice: "Failed to Add Post"
    end
  end

  def edit
  end

  def update
    if @post.update(post_params)
      redirect_to post_path(@post), notice: "Successfully Updated Post"
    else
      redirect_to :back, notice: "Failed to Update Post"
    end
  end

  def destroy
    if @post.delete 
      redirect_to posts_path, notice: "Successfully Deleted Post"
    else
      redirect_to :back
    end
  end

  def upvote
    @post.upvote_by current_user
    redirect_to :back
  end

  def downvote
    @post.downvote_by current_user
    redirect_to :back
  end

  private

  def find_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :link, :description, :image)
  end
end

fitness_app/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

fitness_app/app/controllers/workouts_controller.rb
class WorkoutsController < ApplicationController
	before_action :set_user, only: [:index, :show, :new, :edit]
	before_action :set_workout, only: [:edit, :destroy]

	def index
		@user_workouts = current_user.workouts
	end

	def show
		@user_workout = current_user.workouts.find(params[:id])
	end
	
	def new
		@workout = Workout.new
	end

	def create
		p params
		redirect_to user_workouts_path
	end

	def edit
	end

	def update
		@workout = Workout.find(params[:id])
		@workout.update(title: params[:workout][:title], description: params[:workout][:description])
		redirect_to user_workouts_path
	end

	def destroy
		@workout.destroy
		redirect_to articles_path
	end

	private 
	
	def set_user
		@user = User.find_by(uid: params[:uid])
	end

	def set_workout
		@workout = Workout.find(params[:id])
	end


end

fitness_app/app/helpers/admin_helper.rb
module AdminHelper
end

fitness_app/app/helpers/application_helper.rb
module ApplicationHelper
end

fitness_app/app/helpers/article_helper.rb
module ArticleHelper
end

fitness_app/app/helpers/articles_helper.rb
module ArticlesHelper
end

fitness_app/app/helpers/category_helper.rb
module CategoryHelper
end

fitness_app/app/helpers/comments_helper.rb
module CommentsHelper
end

fitness_app/app/helpers/exercises_helper.rb
module ExercisesHelper
end

fitness_app/app/helpers/motivation_helper.rb
module MotivationHelper
end

fitness_app/app/helpers/posts_helper.rb
module PostsHelper
end

fitness_app/app/helpers/welcome_helper.rb
module WelcomeHelper
end

fitness_app/app/helpers/workouts_helper.rb
module WorkoutsHelper
end

fitness_app/app/views/workouts/_navbar.html.erb
<header>
  <div class="wrapper" class="clearfix">
    <div id="logo">
      <%= link_to "Home", articles_path %>
    </div>
    <nav>
      <% if current_user %>
        <%= link_to "Add New Inspiration", new_post_path, class: "button" %>
        <%= link_to current_user.name, user_workouts_path(current_user) %>
        <%= link_to "Sign out", signout_path, id: "sign_out" %>
      <% else %>
        <%= link_to "Sign in with Facebook", "/auth/facebook", id: "sign_in" %>
      <% end %>
    </nav>
  </div>
</header>

fitness_app/app/views/workouts/_routine.html.erb
		<%= f.label :name %><br />
  	<%= f.text_area :name %>

  	<%= f.label :reps %><br />
  	<%= f.text_area :reps %>

  	<%= f.label :weight %><br />
  	<%= f.text_area :weight %>

fitness_app/app/views/workouts/edit.html.erb
<%= render 'layouts/navbar' %>
<h1>Edit Workout</h1>

<%= form_for @workout, url: user_workouts_path(@user) do |f| %>
  <%= f.label :title %>:
  <%= f.text_field :title %><br />

 Optional <%= f.label :description %>:
  <%= f.text_field :description %><br />

  <%= f.fields_for Routine.new do |builder| %>
	  	<%= builder.label :name %><br />
	  	<%= builder.text_area :name %>

	  	<%= builder.label :reps %><br />
	  	<%= builder.text_area :reps %>

	  	<%= builder.label :weight %><br />
	  	<%= builder.text_area :weight %>

	  	<%= builder.check_box :_destroy %><br />
	  	<%= builder.label :_destroy, "Delete" %>

  <% end %>

<!-- AJAX when title is made and add exercise or show hide or on submit new exercise form shows -->

  <%= f.submit "Update Workout" %>
<% end %>

fitness_app/app/views/workouts/index.html.erb
<%= render 'navbar' %>
<h1>All Made Workouts</h1>

<%= link_to "Create Workout Routine", new_user_workout_path(@user) %>

<p><% @user_workouts.each do |item| %>
	<div>Title: <%= item.title %></div>
		<div>Description: <%= item.description %></div>
		<% item.routines.each do |rout|%>
		<div>Exercise: <%= rout.name %></div>
		<% counter = 0 %>
		<div>Reps: <%= rout.reps[counter] %></div>
		<div>Weight: <%= rout.name[counter] %></div>
		<% counter += 1 %>
		<% end %>
	<%= link_to "Show", user_workout_path(@user, item) %> |
	<%= link_to "Update", edit_user_workout_path(@user, item) %>
<% end %>
</p>
</br>

fitness_app/app/views/workouts/new.html.erb
<%= render 'layouts/navbar' %>
<h1>Create New Workout</h1>

<%= form_for ([current_user, @workout]) do |f| %>
  <%= f.label :title %>:
  <%= f.text_field :title %><br />

 Optional <%= f.label :description %>:
  <%= f.text_field :description %><br />

  <%= f.fields_for Routine.new do |builder| %>
  	<%= render 'routine', :f => builder %>

  <% end %>

  <%= f.submit "Create New Workout" %>
<% end %>

fitness_app/app/views/workouts/show.html.erb
<%= render 'layouts/navbar' %>
<div><%= @user_workout.title %></div>
<% if @user_workout.description != nil %>
    <div>Description: <%= @user_workout.description %></div>
<% end %>
<%= link_to "Update", edit_user_workout_path(@user, @user_workout) %> |
<%= link_to "Delete", @user_workout_path, :method => "delete" %>